### ISSUE TITLE
Towny data removes itself after reload and doesnt auto update on pl3x Map

### ISSUE THREAD

**Issue by NotesYT** [silverwolfg11/Pl3xMap-Towny#7]
When reloading the pl3xtowny plugin all of the towny data removes itself, this happens with a manual reload or a server restart. @silverwolfg11

**Comment by silverwolfg11** [comment]
It looks like one of your towns may be corrupted. The error you posted in the Towny discord indicates that the plugin cannot fetch the name of a mayor of one of your towns. This is usually due to a corrupted town. 

To make this easier to spot, I will add an appropriate error message that displays the town name that is causing the error, but the root issue is not from the Pl3xMap-Towny plugin.

**Comment by NotesYT** [comment]
Thanks so much for the reply, I will try and locate the issue whilst you work on the update so for the future.

**Comment by Agaloth** [comment]
Towns doesn't load with me aswell, new towns gets shown on the map, but towns that were here when installing pl3xmap towny doesn't automatically get rendered and requires a manual render.

**Comment by Agaloth** [comment]
Here is a error that's coming on console if that helps:

[14:35:35 WARN]: [Pl3xMap-Towny] Task #3701610 for Pl3xMap-Towny v1.0.0-ALPHA-2 generated an exception
java.lang.NullPointerException: null
        at me.silverwolfg11.pl3xmaptowny.managers.TownInfoManager.lambda$registerReplacements$0(TownInfoManager.java:104) ~[?:?]
        at me.silverwolfg11.pl3xmaptowny.managers.TownInfoManager.getWindowHTML(TownInfoManager.java:241) ~[?:?]
        at me.silverwolfg11.pl3xmaptowny.managers.TownInfoManager.getClickTooltip(TownInfoManager.java:228) ~[?:?]
        at me.silverwolfg11.pl3xmaptowny.managers.TownyLayerManager.buildTownEntry(TownyLayerManager.java:135) ~[?:?]
        at me.silverwolfg11.pl3xmaptowny.tasks.RenderTownsTask.run(RenderTownsTask.java:53) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-PurpurTracker-"7126ab4"]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-PurpurTracker-"7126ab4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1502) ~[patched_1.16.5.jar:git-PurpurTracker-"7126ab4"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:451) ~[patched_1.16.5.jar:git-PurpurTracker-"7126ab4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1415) ~[patched_1.16.5.jar:git-PurpurTracker-"7126ab4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1141) ~[patched_1.16.5.jar:git-PurpurTracker-"7126ab4"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-PurpurTracker-"7126ab4"]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by silverwolfg11** [comment]
This is hopefully fixed in build [Alpha-3](https://github.com/silverwolfg11/Pl3xMap-Towny/releases/tag/v1.0.0-alpha-3) courtesy of AAigars for noticing the issue and the PR to resolve.

**Comment by Agaloth** [comment]
It is indeed fixed, thanks!
